export enum listProductsImages{
    'ACEITUNA DE MESA'='aceitunas.jpg',
    'Bellotas recolectadas'='bellota.jpg',
    'CEREALES CULTIVADOS'='cereales.jpg',
    'Caracoles'='caracoles.jpeg',
    'Castañas recolectadas' = 'castanas.jpg',
    'FRESAS Y OTROS BERRIES CULTIVADOS' = 'fresas.jpg',
    'Espárragos silvestres recolectados' = 'esparragos.jpg',
    'FRUTALES SUBTROPICALES CULTIVADOS' = 'frutalessubtropicales.jpg',
    'HORTALIZAS CULTIVADAS (POR ESPECIE)' = 'hortalizas.jpeg',
    'Huevos' = 'huevos.jpg',
    'Jalea real' = 'jaleareal.jpg',
    'LEGUMBRES CULTIVADAS (POR ESPECIE)' ='legumbres.jpg',
    'Miel' = 'Miel.jpeg',
    'OTRAS FRUTAS Y FRUTOS CULTIVADOS (POR ESPECIE)'='otrasfrutas.jpg',
    'Otros frutos silvestres recolectados'='frutossilvestres.jpg',
    'PATATAS CULTIVADAS' = 'patatas.jpg',
    'Piñones recolectados' ='pinones.jpg',
    'Plantas aromáticas recolectadas' = 'plantasaromaticas.jpg',
    'Polen' = 'polen.jpg',
    'Propóleo' = 'propoleo.jpg',
    'SETAS CULTIVADAS' = 'setas.jpg',
    'Setas silvestres (por especies) recolectadas' = 'setassilvestres.jpg',
    'Tagarninas recolectadas' = 'tagarninas.jpg'
}